import { supabase } from "@/lib/supabase";
import { generateFileName, sleep } from "@/lib/utils";
import { TIER_ENGINES, type ContentTier } from "@/lib/types";
import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { athlete_id, template_id } = body;

  if (!athlete_id || !template_id) {
    return new Response(
      JSON.stringify({ error: "athlete_id and template_id are required" }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      function send(data: Record<string, unknown>) {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      }

      try {
        // Fetch athlete data
        const { data: athlete, error: athleteErr } = await supabase
          .from("athletes")
          .select("*")
          .eq("id", athlete_id)
          .single();

        if (athleteErr || !athlete) {
          send({ type: "error", message: "Athlete not found" });
          controller.close();
          return;
        }

        // Fetch template data
        const { data: template, error: templateErr } = await supabase
          .from("templates")
          .select("*")
          .eq("id", template_id)
          .single();

        if (templateErr || !template) {
          send({ type: "error", message: "Template not found" });
          controller.close();
          return;
        }

        const tier = template.content_tier as ContentTier;
        const engine = TIER_ENGINES[tier];
        const fileName = generateFileName(
          athlete.name,
          template.category,
          template.location
        );

        // Step 1: Assemble prompt
        send({ type: "step", step: "prompt", status: "active", detail: "Building prompt from athlete + template data" });
        await sleep(1500);

        const prompt = `Generate a cinematic video of ${athlete.name} (${athlete.sport}) ${template.action} at ${template.location}. ` +
          `Wardrobe: ${template.wardrobe}. Lighting: ${template.lighting}. ` +
          `Camera: ${template.camera_angle}. Audio: ${template.audio_track}.`;

        send({ type: "step", step: "prompt", status: "done", detail: `Prompt assembled (${prompt.length} chars)` });

        // Step 2: SIMULATED - Claude AI validation
        send({ type: "step", step: "validate", status: "active", detail: "Validating prompt with Claude AI..." });
        await sleep(2000);
        // SIMULATED: In production, this would call the Claude API to validate
        // the prompt for safety, coherence, and brand alignment
        send({ type: "step", step: "validate", status: "done", detail: "Prompt validated — safe & on-brand" });

        // Step 3: SIMULATED - Video generation via tier-appropriate engine
        send({ type: "step", step: "generate", status: "active", detail: `Generating via ${engine}...` });
        await sleep(3000);
        // SIMULATED: In production, this would call the appropriate video generation API:
        // - Premium → Runway Gen-4.5 API
        // - Standard → Kling 3.0 API
        // - Social → Vidu Q3 Pro API
        const outputUrl = `https://storage.example.com/generated-videos/${fileName}`;
        send({ type: "step", step: "generate", status: "done", detail: `Video generated by ${engine}` });

        // Step 4: SIMULATED - Face scoring
        send({ type: "step", step: "score", status: "active", detail: "Analyzing face fidelity..." });
        await sleep(2000);
        // SIMULATED: In production, this would use a face comparison API to
        // score how well the generated face matches the athlete's reference photos
        const faceScore = Math.floor(Math.random() * 16) + 85; // 85-100
        send({ type: "step", step: "score", status: "done", detail: `Face score: ${faceScore}/100` });

        // Step 5: Quality routing based on face score
        send({ type: "step", step: "route", status: "active", detail: "Determining quality route..." });
        await sleep(1000);

        let jobStatus: string;
        if (faceScore >= 90) {
          jobStatus = "approved";
        } else if (faceScore >= 85) {
          jobStatus = "needs_review";
        } else {
          jobStatus = "rejected";
        }

        send({
          type: "step",
          step: "route",
          status: "done",
          detail: `Routed: ${jobStatus} (score ${faceScore} ${faceScore >= 90 ? "≥ 90" : faceScore >= 85 ? "85-89" : "< 85"})`,
        });

        // Create job record in database
        const { error: jobErr } = await supabase.from("jobs").insert({
          athlete_id,
          template_id,
          status: jobStatus,
          face_score: faceScore,
          output_url: outputUrl,
          file_name: fileName,
          prompt,
          engine,
        });

        if (jobErr) {
          console.error("Failed to create job record:", jobErr);
        }

        // SIMULATED: Send webhook notification if configured
        // In production, this would POST to the configured webhook_url
        // with the job result payload

        // Send final result
        send({
          type: "result",
          success: true,
          fileName,
          outputUrl,
          faceScore,
          status: jobStatus,
          engine,
          prompt,
        });
      } catch (error) {
        send({
          type: "error",
          message: error instanceof Error ? error.message : "Generation failed",
        });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
