import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

const supabase = createClient(supabaseUrl, supabaseKey);

const templates = [
  // PREMIUM tier — Luxury Travel (1-3)
  {
    category: "Luxury Travel",
    variant: "Private Jet Arrival",
    action: "stepping off a private jet onto a sun-drenched tarmac, tropical island visible in background",
    location: "Maldives",
    wardrobe: "tailored linen suit, designer sunglasses",
    lighting: "Golden hour, warm tones",
    camera_angle: "Low-angle tracking shot",
    audio_track: "luxury_warm_01.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "premium",
  },
  {
    category: "Luxury Travel",
    variant: "Yacht Deck Sunset",
    action: "standing on the bow of a mega-yacht watching the sunset, ocean breeze",
    location: "Amalfi Coast, Italy",
    wardrobe: "white linen shirt, rolled sleeves",
    lighting: "Golden sunset backlighting",
    camera_angle: "Slow orbital shot",
    audio_track: "luxury_warm_02.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "premium",
  },
  {
    category: "Luxury Travel",
    variant: "Penthouse Arrival",
    action: "walking into a glass-walled penthouse suite with panoramic city views",
    location: "Dubai Marina",
    wardrobe: "tailored black suit, no tie",
    lighting: "Blue hour, city lights below",
    camera_angle: "Following shot from behind, reveals view",
    audio_track: "luxury_warm_03.mp3",
    platforms: "Reels, YT",
    content_tier: "premium",
  },
  // PREMIUM tier — Fine Dining (4-6)
  {
    category: "Fine Dining",
    variant: "Michelin Table",
    action: "seated at an intimate table, raising a glass, plated gourmet meal in front",
    location: "rooftop restaurant, city skyline through floor-to-ceiling windows",
    wardrobe: "fitted blazer, open collar shirt",
    lighting: "Warm candlelight, soft ambient",
    camera_angle: "Medium close-up, shallow depth of field",
    audio_track: "dining_jazz_01.mp3",
    platforms: "IG Feed, Reels",
    content_tier: "premium",
  },
  {
    category: "Fine Dining",
    variant: "Chef's Counter",
    action: "sitting at a chef's counter watching food prepared, nodding in appreciation",
    location: "exclusive omakase restaurant, wood and stone interior",
    wardrobe: "premium casual, dark tones",
    lighting: "Warm overhead spots, moody",
    camera_angle: "Side profile medium shot",
    audio_track: "dining_jazz_02.mp3",
    platforms: "IG Feed, Reels",
    content_tier: "premium",
  },
  {
    category: "Fine Dining",
    variant: "Wine Toast",
    action: "toasting with a wine glass on an outdoor terrace, coastal view behind",
    location: "Santorini cliffside restaurant",
    wardrobe: "white button-down, sleeves rolled",
    lighting: "Late afternoon golden sun",
    camera_angle: "Close-up on face then pull back to reveal setting",
    audio_track: "dining_jazz_03.mp3",
    platforms: "Reels, TikTok",
    content_tier: "premium",
  },
  // PREMIUM tier — Wellness & Mindfulness (7-9)
  {
    category: "Wellness & Mindfulness",
    variant: "Sunrise Meditation",
    action: "meditating cross-legged at sunrise on a cliffside, ocean waves crashing below",
    location: "Bali cliffside temple",
    wardrobe: "minimal athletic wear, earth tones",
    lighting: "Soft warm sunrise, golden rim light",
    camera_angle: "Wide establishing shot, slow push-in",
    audio_track: "wellness_ambient_01.mp3",
    platforms: "Reels, IG Feed",
    content_tier: "premium",
  },
  {
    category: "Wellness & Mindfulness",
    variant: "Forest Retreat",
    action: "walking mindfully through a misty ancient forest, touching tree bark",
    location: "Pacific Northwest old-growth forest",
    wardrobe: "premium athleisure, muted greens",
    lighting: "Diffused morning fog, god rays",
    camera_angle: "Slow tracking shot at eye level",
    audio_track: "wellness_ambient_02.mp3",
    platforms: "Reels, IG Feed",
    content_tier: "premium",
  },
  {
    category: "Wellness & Mindfulness",
    variant: "Hot Spring",
    action: "relaxing in a natural hot spring surrounded by snow-capped mountains",
    location: "Iceland geothermal pools",
    wardrobe: "minimal, shoulders visible",
    lighting: "Overcast soft light, steam rising",
    camera_angle: "Medium wide, steam adds atmosphere",
    audio_track: "wellness_ambient_03.mp3",
    platforms: "Reels, TikTok",
    content_tier: "premium",
  },
  // PREMIUM tier — Motorsports & Cars (10-12)
  {
    category: "Motorsports & Cars",
    variant: "Supercar Desert",
    action: "leaning against an exotic supercar in an empty desert highway, arms crossed confidently",
    location: "Nevada desert highway at dusk",
    wardrobe: "premium streetwear, designer jacket",
    lighting: "Dramatic dusk sky, orange and purple",
    camera_angle: "Low wide angle, car and athlete fill frame",
    audio_track: "cars_bass_01.mp3",
    platforms: "YouTube, TikTok",
    content_tier: "premium",
  },
  {
    category: "Motorsports & Cars",
    variant: "Track Day",
    action: "stepping out of a race car on a track, helmet in hand, walking toward camera",
    location: "professional race circuit, pit lane",
    wardrobe: "racing suit unzipped to waist, t-shirt underneath",
    lighting: "Bright midday sun, heat shimmer",
    camera_angle: "Slow-motion hero walk toward camera",
    audio_track: "cars_bass_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "premium",
  },
  {
    category: "Motorsports & Cars",
    variant: "Garage Collection",
    action: "walking through a private car collection garage, trailing fingers along car hoods",
    location: "luxury private garage, polished concrete",
    wardrobe: "tailored casual, premium sneakers",
    lighting: "Cool LED strips, warm accent spots on cars",
    camera_angle: "Tracking shot following from side",
    audio_track: "cars_bass_03.mp3",
    platforms: "YouTube, Reels",
    content_tier: "premium",
  },
  // PREMIUM tier — Yacht & Water (13-15)
  {
    category: "Yacht & Water",
    variant: "Open Water",
    action: "standing on the bow of a yacht cutting through crystalline blue water, wind in hair",
    location: "Greek Islands, coastal cliffs behind",
    wardrobe: "swim trunks, open linen shirt",
    lighting: "Bright midday tropical sun, water reflections",
    camera_angle: "Aerial tracking shot from side",
    audio_track: "ocean_deep_01.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "premium",
  },
  {
    category: "Yacht & Water",
    variant: "Jet Ski",
    action: "riding a jet ski at high speed, spray behind, laughing",
    location: "turquoise Caribbean water, white sand island behind",
    wardrobe: "board shorts, no shirt, sunglasses",
    lighting: "High noon sun, sparkling water",
    camera_angle: "Tracking from boat alongside",
    audio_track: "ocean_deep_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "premium",
  },
  {
    category: "Yacht & Water",
    variant: "Underwater",
    action: "diving off the back of a yacht into clear water, underwater shot of entry",
    location: "Maldives atoll, reef visible",
    wardrobe: "swim trunks",
    lighting: "Underwater dappled sunlight",
    camera_angle: "Split shot: above and below waterline",
    audio_track: "ocean_deep_03.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "premium",
  },
  // PREMIUM tier — Business & Leadership (16-18)
  {
    category: "Business & Leadership",
    variant: "Boardroom",
    action: "standing at the head of a boardroom table, city skyline behind, commanding presence",
    location: "corner office, floor-to-ceiling glass, downtown skyline",
    wardrobe: "perfectly tailored navy suit, power tie",
    lighting: "Clean corporate, natural window light",
    camera_angle: "Slow push-in to medium shot",
    audio_track: "business_clean_01.mp3",
    platforms: "LinkedIn, YT, IG Feed",
    content_tier: "premium",
  },
  {
    category: "Business & Leadership",
    variant: "Rooftop Office",
    action: "reviewing documents on a rooftop terrace office, city below",
    location: "modern rooftop workspace, skyline panorama",
    wardrobe: "fitted dress shirt, sleeves rolled, premium watch",
    lighting: "Late afternoon golden light",
    camera_angle: "Medium shot, rack focus from documents to face",
    audio_track: "business_clean_02.mp3",
    platforms: "LinkedIn, YT",
    content_tier: "premium",
  },
  {
    category: "Business & Leadership",
    variant: "Keynote Stage",
    action: "walking onto a stage in front of a large audience, spotlight hitting, confident stride",
    location: "modern conference venue, large LED screen behind",
    wardrobe: "all-black fitted outfit, minimal",
    lighting: "Dramatic stage spotlight, dark audience",
    camera_angle: "Wide shot then cut to medium as they reach center stage",
    audio_track: "business_clean_03.mp3",
    platforms: "LinkedIn, YT, TikTok",
    content_tier: "premium",
  },
  // STANDARD tier — Outdoor Adventure (19-21)
  {
    category: "Outdoor Adventure",
    variant: "Mountain Summit",
    action: "hiking a dramatic mountain trail at golden hour, wind in hair, panoramic valley below",
    location: "Swiss Alps ridgeline",
    wardrobe: "premium hiking gear, earth tones",
    lighting: "Golden hour, natural warm light",
    camera_angle: "Wide aerial pull-back reveal",
    audio_track: "adventure_epic_01.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Outdoor Adventure",
    variant: "Cliff Overlook",
    action: "standing at the edge of a cliff overlooking a vast canyon, arms spread wide",
    location: "Grand Canyon South Rim",
    wardrobe: "technical outdoor jacket, boots",
    lighting: "Dramatic sunrise side-lighting",
    camera_angle: "Drone pull-back from close-up to wide",
    audio_track: "adventure_epic_02.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "standard",
  },
  {
    category: "Outdoor Adventure",
    variant: "Waterfall",
    action: "standing beneath a massive waterfall, mist swirling, looking up in awe",
    location: "Iceland volcanic waterfall",
    wardrobe: "waterproof athletic gear",
    lighting: "Overcast dramatic, rainbow in mist",
    camera_angle: "Low-angle looking up with athlete",
    audio_track: "adventure_epic_03.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  // STANDARD tier — Urban Nightlife (22-24)
  {
    category: "Urban Nightlife",
    variant: "Neon Streets",
    action: "walking confidently through neon-lit city streets, luxury car parked behind, reflections on wet pavement",
    location: "Tokyo Shibuya crossing at night",
    wardrobe: "designer streetwear, chains, premium sneakers",
    lighting: "Neon ambient, cool blues and pinks",
    camera_angle: "Slow-motion tracking from front",
    audio_track: "nightlife_deep_01.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Urban Nightlife",
    variant: "Rooftop Party",
    action: "arriving at an exclusive rooftop party, city lights sparkling below, crowd parting",
    location: "downtown LA rooftop bar",
    wardrobe: "all-black fitted outfit, statement watch",
    lighting: "Ambient string lights, city glow",
    camera_angle: "Following shot from behind, reveals rooftop",
    audio_track: "nightlife_deep_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Urban Nightlife",
    variant: "Club Entrance",
    action: "stepping out of a luxury SUV at a club entrance, paparazzi flashes",
    location: "Miami Beach nightclub district",
    wardrobe: "designer fit, bold accessories",
    lighting: "Flash photography mixed with neon",
    camera_angle: "Paparazzi-style multiple angles",
    audio_track: "nightlife_deep_03.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  // STANDARD tier — Fitness & Training (25-27)
  {
    category: "Fitness & Training",
    variant: "Gym Power",
    action: "performing explosive box jumps in a premium gym, sweat glistening, raw athletic energy",
    location: "elite training facility, dark industrial",
    wardrobe: "premium compression gear, training shoes",
    lighting: "High contrast dramatic, overhead spots",
    camera_angle: "Dynamic multi-angle, slow-mo on peak",
    audio_track: "fitness_hype_01.mp3",
    platforms: "TikTok, Reels, YT Shorts",
    content_tier: "standard",
  },
  {
    category: "Fitness & Training",
    variant: "Field Training",
    action: "running agility drills on a pristine football field, cutting hard, explosive speed",
    location: "empty professional stadium field",
    wardrobe: "training shorts, compression top, cleats",
    lighting: "Late afternoon stadium lights warming up",
    camera_angle: "Ground-level tracking, emphasize speed",
    audio_track: "fitness_hype_02.mp3",
    platforms: "TikTok, Reels, YT Shorts",
    content_tier: "standard",
  },
  {
    category: "Fitness & Training",
    variant: "Weight Room",
    action: "deadlifting heavy weight with perfect form, chalk dust in the air, intense focus",
    location: "elite strength facility, exposed brick",
    wardrobe: "tank top, training shorts, lifting belt",
    lighting: "Moody overhead, shaft of light on athlete",
    camera_angle: "Side profile, slow-motion lift",
    audio_track: "fitness_hype_03.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  // STANDARD tier — Beach & Resort (28-30)
  {
    category: "Beach & Resort",
    variant: "Infinity Pool",
    action: "lounging by an infinity pool overlooking turquoise ocean, cocktail in hand, resort cabana",
    location: "Bali luxury resort, rice terraces behind",
    wardrobe: "premium swim trunks, designer sunglasses",
    lighting: "Bright tropical sun, water reflections",
    camera_angle: "Slow pan, medium shot",
    audio_track: "beach_chill_01.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "standard",
  },
  {
    category: "Beach & Resort",
    variant: "Beach Walk",
    action: "walking along a pristine white sand beach at sunset, waves lapping at feet",
    location: "Tulum, Mexico",
    wardrobe: "linen pants rolled up, open shirt",
    lighting: "Golden sunset, long shadows",
    camera_angle: "Tracking from side, waves in frame",
    audio_track: "beach_chill_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Beach & Resort",
    variant: "Cabana",
    action: "relaxing in a private beach cabana, reading, ocean breeze moving curtains",
    location: "Seychelles private island",
    wardrobe: "resort casual, premium swim shorts",
    lighting: "Dappled shade, bright ocean behind",
    camera_angle: "Medium shot from beach looking in",
    audio_track: "beach_chill_03.mp3",
    platforms: "Reels, IG Feed",
    content_tier: "standard",
  },
  // STANDARD tier — Fashion & Streetwear (31-33)
  {
    category: "Fashion & Streetwear",
    variant: "Art District",
    action: "walking through an art district in a curated streetwear fit, cinematic slow-motion",
    location: "Brooklyn DUMBO, graffiti walls",
    wardrobe: "designer streetwear, layered, statement sneakers",
    lighting: "Natural daylight, urban setting",
    camera_angle: "Cinematic slow-motion, full body",
    audio_track: "fashion_cool_01.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Fashion & Streetwear",
    variant: "Mural Wall",
    action: "leaning against a massive colorful mural, adjusting jacket, looking off camera",
    location: "Wynwood Walls, Miami",
    wardrobe: "premium casual, bold colors matching mural",
    lighting: "Bright midday, vibrant colors",
    camera_angle: "Wide then punch in to medium",
    audio_track: "fashion_cool_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Fashion & Streetwear",
    variant: "Sneaker Drop",
    action: "lacing up exclusive sneakers on a rooftop, city behind, standing up and walking away",
    location: "downtown rooftop, skyline backdrop",
    wardrobe: "full streetwear fit built around the shoes",
    lighting: "Overcast even light, urban",
    camera_angle: "Start on shoes, tilt up to full body",
    audio_track: "fashion_cool_03.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  // STANDARD tier — Studio Portrait (34-36)
  {
    category: "Studio Portrait",
    variant: "Editorial",
    action: "striking a high-fashion editorial pose, turning slowly toward camera, intense eye contact",
    location: "professional photo studio, seamless white background",
    wardrobe: "high-fashion editorial, tailored",
    lighting: "Dramatic studio lighting, hard shadows",
    camera_angle: "Medium portrait, slow push-in",
    audio_track: "portrait_minimal_01.mp3",
    platforms: "IG Feed, LinkedIn",
    content_tier: "standard",
  },
  {
    category: "Studio Portrait",
    variant: "Athlete Portrait",
    action: "standing with arms crossed, athlete power pose, slight head tilt",
    location: "dark studio, single spotlight",
    wardrobe: "fitted athletic compression, or team gear",
    lighting: "Single dramatic key light, dark background",
    camera_angle: "Medium shot, slight low angle for power",
    audio_track: "portrait_minimal_02.mp3",
    platforms: "IG Feed, LinkedIn",
    content_tier: "standard",
  },
  {
    category: "Studio Portrait",
    variant: "Casual Studio",
    action: "sitting on a stool, relaxed pose, genuine laugh mid-conversation",
    location: "warm-toned studio, blurred lights behind",
    wardrobe: "premium casual, authentic vibe",
    lighting: "Warm soft studio, multiple sources",
    camera_angle: "Close-up, shallow depth of field",
    audio_track: "portrait_minimal_03.mp3",
    platforms: "IG Feed",
    content_tier: "standard",
  },
  // STANDARD tier — Game Day (37-39)
  {
    category: "Game Day",
    variant: "Tunnel Walk",
    action: "walking through a stadium tunnel toward the field, crowd noise rising, dramatic lighting",
    location: "major stadium tunnel, light at the end",
    wardrobe: "game jersey or warm-up gear, team colors",
    lighting: "Dramatic tunnel lighting, bright field ahead",
    camera_angle: "Low-angle hero walk, slow-motion",
    audio_track: "gameday_hype_01.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Game Day",
    variant: "Sideline Focus",
    action: "standing on the sideline, helmet in hand, watching the game with intense focus",
    location: "packed stadium, 50-yard line",
    wardrobe: "full game uniform",
    lighting: "Stadium lights, evening game atmosphere",
    camera_angle: "Medium close-up, crowd blurred behind",
    audio_track: "gameday_hype_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Game Day",
    variant: "Celebration",
    action: "arms raised in victory celebration, confetti falling, teammates nearby",
    location: "stadium end zone, scoreboard visible",
    wardrobe: "game uniform, grass stains",
    lighting: "Bright stadium lights, confetti catching light",
    camera_angle: "Wide then punch to close-up on face",
    audio_track: "gameday_hype_03.mp3",
    platforms: "TikTok, Reels, YT",
    content_tier: "standard",
  },
  // STANDARD tier — Charity & Community (40-42)
  {
    category: "Charity & Community",
    variant: "Youth Camp",
    action: "high-fiving kids at a community football camp, genuine smile, mentor energy",
    location: "community park field, banners and cones",
    wardrobe: "AiC branded t-shirt, athletic shorts",
    lighting: "Warm natural outdoor, afternoon",
    camera_angle: "Candid medium shot, handheld feel",
    audio_track: "community_warm_01.mp3",
    platforms: "IG Feed, LinkedIn, YT",
    content_tier: "standard",
  },
  {
    category: "Charity & Community",
    variant: "School Visit",
    action: "speaking to a classroom of students, animated gesture, kids engaged",
    location: "elementary school classroom",
    wardrobe: "smart casual, approachable",
    lighting: "Natural window light, classroom ambient",
    camera_angle: "Over-the-shoulder from students POV",
    audio_track: "community_warm_02.mp3",
    platforms: "IG Feed, LinkedIn",
    content_tier: "standard",
  },
  {
    category: "Charity & Community",
    variant: "Food Drive",
    action: "helping distribute food boxes, carrying a box, smiling at volunteer",
    location: "community center, organized box station",
    wardrobe: "casual, volunteer t-shirt",
    lighting: "Indoor fluorescent mixed with window light",
    camera_angle: "Documentary style, medium shot",
    audio_track: "community_warm_03.mp3",
    platforms: "IG Feed, LinkedIn, YT",
    content_tier: "standard",
  },
  // STANDARD tier — Music & Entertainment (43-45)
  {
    category: "Music & Entertainment",
    variant: "VIP Lounge",
    action: "sitting in a VIP lounge section, DJ booth in background, ambient vibes, head nodding to beat",
    location: "exclusive nightclub VIP area",
    wardrobe: "designer outfit, statement accessories, chains",
    lighting: "Purple and blue ambient, moving lights",
    camera_angle: "Smooth steady track, medium shot",
    audio_track: "entertainment_vibe_01.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Music & Entertainment",
    variant: "Studio Session",
    action: "in a recording studio, headphones around neck, vibing to playback",
    location: "professional recording studio, mixing board",
    wardrobe: "premium streetwear, relaxed",
    lighting: "Dim studio ambient, LED accents",
    camera_angle: "Close-up face then pull back to show studio",
    audio_track: "entertainment_vibe_02.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
  {
    category: "Music & Entertainment",
    variant: "Concert VIP",
    action: "watching a concert from backstage, stage lights flashing, crowd visible, genuine enjoyment",
    location: "major concert venue, backstage area",
    wardrobe: "all-black premium, backstage pass visible",
    lighting: "Stage light bleed, dramatic color wash",
    camera_angle: "Medium shot, concert as backdrop",
    audio_track: "entertainment_vibe_03.mp3",
    platforms: "TikTok, Reels",
    content_tier: "standard",
  },
];

async function seed() {
  console.log("Seeding 45 prompt templates...");

  const { data: existing } = await supabase.from("templates").select("id").limit(1);

  if (existing && existing.length > 0) {
    console.log("Templates already exist. Skipping seed.");
    return;
  }

  const { error } = await supabase.from("templates").insert(templates);

  if (error) {
    console.error("Seed failed:", error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${templates.length} templates.`);

  // Create storage buckets
  try {
    await supabase.storage.createBucket("reference-photos", { public: true });
    console.log("Created reference-photos bucket");
  } catch {
    console.log("reference-photos bucket may already exist");
  }

  try {
    await supabase.storage.createBucket("generated-videos", { public: true });
    console.log("Created generated-videos bucket");
  } catch {
    console.log("generated-videos bucket may already exist");
  }
}

seed().catch(console.error);
