export const SIDEBAR_ITEMS = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Generate", href: "/generate", icon: "Sparkles" },
  { label: "Athletes", href: "/athletes", icon: "Users" },
  { label: "Templates", href: "/templates", icon: "LayoutTemplate" },
  { label: "Queue", href: "/queue", icon: "ListChecks" },
  { label: "Settings", href: "/settings", icon: "Settings" },
] as const;

export const POSITIONS = ["QB", "RB", "WR", "TE", "OL", "IOL", "OT", "DL", "EDGE", "LB", "CB", "S"] as const;

export const STYLE_PREFERENCES = ["streetwear", "formal", "athleisure", "casual", "editorial"] as const;

export const CLASS_YEARS = [2025, 2026, 2027, 2028, 2029, 2030] as const;

export const US_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
] as const;
